### ISSUE TITLE
PDF to Doc, Problems with multiple pages and page orientation

### ISSUE THREAD

**Issue by dhenry437** [Stirling-Tools/Stirling-PDF#1060]
PDF to Doc works great, its able to convert files I've had problems with using other similar services.

Two problems so far:
 - Multi page PDFs, it seems to overlay all the pages on one page.
 - It doesn't seem to detect that the PDF is landscape, but change the page orientation in word after the fact and it looks fine.

**Comment by Frooodle** [comment]
multi page part should be fixed now can you please try again

**Comment by dhenry437** [comment]
still merges the pages (also still not detecting landscape)

im on version 0.23.0, do i need to switch branch?

**Comment by Frooodle** [comment]
Pdf to doc uses libre office so if you are not using docker it will depend on what version you have installed and if it had a bug etc

I suggest you try update your libre office

**Comment by STREKOZZEL** [comment]
Frooodle, thank you.
Seems this problem with LibreOffice version 7.4.7-1+deb12u1 from Debian repo. With LibreOffice version 7.6.7 or 24.2.3 it works normal.
