### ISSUE TITLE
The Web page is wrong

### ISSUE THREAD

**Issue by IamTaoChen** [Stirling-Tools/Stirling-PDF#1261]
when I pull the latest(0.24) docker image and start, the web become this
<img width="1429" alt="image" src="https://github.com/Stirling-Tools/Stirling-PDF/assets/42793494/3d7aba6a-f09e-4f7b-9bf1-61ea2bd67aff">

**Comment by mkamranmazhar** [comment]
Yes, this is exactly what happened to me.

**Comment by Ludy87** [comment]
Give us more information, a log entry would be desirable

**Comment by LeaderbotX400** [comment]
I have the same issue, though only when I go through a reverse proxy with SSL.

Something about resources being requested in HTTP and not HTTPS

**Comment by Frooodle** [comment]
Another saw this issue and mentioned it was resolved by changing their reverse proxy from direct docker connection to IP:port

We are looking into this issue but also not sure of the cause at the moment

**Comment by how1999** [comment]
我也遇到了这样的问题，通过nginx反代后，就出现了

**Comment by IamTaoChen** [comment]
> I have the same issue, though only when I go through a reverse proxy with SSL.
> 
> Something about resources being requested in HTTP and not HTTPS

I also noticed this problem when I tried to use OIDC. the `redirect_url` is `http`

**Comment by IamTaoChen** [comment]
> Give us more information, a log entry would be desirable

<img width="736" alt="image" src="https://github.com/Stirling-Tools/Stirling-PDF/assets/42793494/b87712a7-0f0a-4fe5-a0f2-4e7547f515fa">
Is this OK?

**Comment by mkamranmazhar** [comment]
I've tested both with HTTP/HTTPS.
Still the same problem.
Please check both URL:

https://pdf.shinetechpro.com
http://154.12.224.81:8001

**Comment by Frooodle** [comment]
> I've tested both with HTTP/HTTPS.
> Still the same problem.
> Please check both URL:
> 
> https://pdf.shinetechpro.com
> http://154.12.224.81:8001

Http loads fine for me here and I think any direct IP would too as well

It seems to be issue with reverse proxy when combined with it not connecting via IP from what I have seen people reporting

**Comment by Frooodle** [comment]
what reverse proxy are you all using, can any share their configs?

**Comment by IamTaoChen** [comment]
> what reverse proxy are you all using, can any share their configs?

> what reverse proxy are you all using, can any share their configs?

I use `apache2`

```conf
<VirtualHost *:443>
    ServerName example.com

    SSLEngine on
  # configure for ssl, this is global configuration.
  SSLCertificateFile example.com.pem
  SSLCertificateKeyFile  example.com.pem.key

    ProxyPreserveHost On
    ProxyRequests Off
    RewriteEngine On

    RewriteCond %{HTTP:Connection} Upgrade [NC]
    RewriteCond %{HTTP:Upgrade} websocket [NC]
    RewriteRule ^/?(.*) ws://stirling-pdf:8080/$1  [P,L]

    <Location />
        RequestHeader set X_FORWARDED_PROTO 'https'
        RequestHeader set X-Forwarded-Ssl on
        RequestHeader set X-Forwarded-Port "443"
        ProxyPass http://stirling-pdf:8080/
        ProxyPassReverse http://stirling-pdf:8080/
    </Location>   
    ErrorLog ${APACHE_LOG_DIR}/pdf_error.log
	# CustomLog ${APACHE_LOG_DIR}/pdf_access.log combined
        
</VirtualHost>

```

**Comment by LeaderbotX400** [comment]
> what reverse proxy are you all using, can any share their configs?

```yaml
  traefik:
    # The official v2 Traefik docker image
    image: traefik:latest
    ports:
      - 80:80
      - 8282:8080
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock:ro'
    # Enables the web UI and tells Traefik to listen to docker
    command:
      - --api.insecure=true
      - --providers.docker=true
      - --entryPoints.http.address=:80
      - --providers.docker.exposedByDefault=false
      - --entryPoints.http.forwardedHeaders.insecure
      - --entryPoints.http.proxyProtocol.insecure
    restart: 'always'

  stirling-pdf:
    container_name: Stirling-PDF-Security
    image: frooodle/s-pdf:latest
    deploy:
      resources:
        limits:
          memory: 4G
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl -f http://localhost:8080/api/v1/info/status | grep -q 'UP' && curl -fL http://localhost:8080/ | grep -q 'Please sign in'"
        ]
      interval: 5s
      timeout: 10s
      retries: 16
    ports:
      - 8080:8080
    volumes:
      - ./data:/usr/share/tessdata:rw
      - ./config:/configs:rw
      - ./logs:/logs:rw
    labels:
      traefik.enable: true
      traefik.http.routers.stirling-pdf.rule: Host(`pdf.[REDACTED].com`)
    environment:
      DOCKER_ENABLE_SECURITY: true
      SECURITY_ENABLELOGIN: true
      SECURITY_OAUTH2_ENABLED: true
      SECURITY_OAUTH2_AUTOCREATEUSER: true # This is set to true to allow auto-creation of non-existing users in Striling-PDF
      SECURITY_OAUTH2_ISSUER: "https://auth.[REDACTED].com/application/o/stirling-pdf/" # Change with any other provider that supports OpenID Connect Discovery (/.well-known/openid-configuration) end-point
      SECURITY_OAUTH2_CLIENTID: "[REDACTED]" # Client ID from your provider
      SECURITY_OAUTH2_CLIENTSECRET: "[REDACTED]" # Client Secret from your provider
      PUID: 1002
      PGID: 1002
      UMASK: "022"
      SYSTEM_DEFAULTLOCALE: en-US
      UI_APPNAME: Stirling-PDF
      UI_HOMEDESCRIPTION: Demo site for Stirling-PDF Latest with Security
      UI_APPNAMENAVBAR: Stirling-PDF Latest
      SYSTEM_MAXFILESIZE: "100"
      METRICS_ENABLED: "true"
      SYSTEM_GOOGLEVISIBILITY: "false"
    restart: on-failure:5
```

**Comment by While4** [comment]
This seems to be caused by Mixed Content.

**Comment by mkamranmazhar** [comment]
> what reverse proxy are you all using, can any share their configs?

![Screenshot 2024-05-22 092008](https://github.com/Stirling-Tools/Stirling-PDF/assets/106512746/cca051d1-f7c4-48ec-b53c-6e7b4d3641fe)

aaPanel reverse proxy.

**Comment by gwado** [comment]
Until these calls are resolved, you can add this line to your domain-ssl.conf :

```
# Add Content-Security-Policy to force use of HTTPS
Header always set Content-Security-Policy "upgrade-insecure-requests;"
```

Then reload your apache2 configuration.

**Comment by mkamranmazhar** [comment]
> Until these calls are resolved, you can add this line to your domain-ssl.conf :
> 
> ```
> # Add Content-Security-Policy to force use of HTTPS
> Header always set Content-Security-Policy "upgrade-insecure-requests;"
> ```
> 
> Then reload your apache2 configuration.

and for Nginx?

**Comment by dogthor1st** [comment]
Using HAProxy on my OPNsense firewall and had the same issue when using it as a direct reverse proxy.

I solved it by using a nginx container as a reverse proxy directly before HAProxy.

So this is my file architecture for Docker :

```bash
./stirling-pdf/
|-- docker-compose.yaml
`-- nginx
    |-- default.conf
    |-- dockerfile
    `-- ssl
        |-- gen-ssl.sh
        |-- server.crt
        `-- server.key
```

docker-compose.yaml file :

```yaml
version: '3.3'
services:
  stirling-pdf:
    image: frooodle/s-pdf:latest
    networks:
      - stirling-net
    volumes:
      - ./configs/trainingData:/usr/share/tessdata #Required for extra OCR languages
      - ./configs/extraConfigs:/configs
#      - /location/of/customFiles:/customFiles/
      - ./logs:/logs/
    environment:
      - DOCKER_ENABLE_SECURITY=true
      - INSTALL_BOOK_AND_ADVANCED_HTML_OPS=true
      - LANGS=fr-FR
    restart: unless-stopped

  nginx:
    networks:
      - stirling-net
    build:
        context: ./nginx
    volumes: 
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/ssl:/etc/nginx/ssl
    ports:
      - '1198:443'
    restart: unless-stopped

networks:
  stirling-net:
```

default.conf for nginx : 

```bash
server {
  listen 443 ssl http2;

  ssl_certificate  /etc/nginx/ssl/server.crt;
  ssl_certificate_key /etc/nginx/ssl/server.key;

  # Allow large attachments
  client_max_body_size 128M;

  location / {
    proxy_pass http://stirling-pdf:8080;
    proxy_http_version 1.1;
    proxy_set_header Host $host;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
  }

}
``` 

dockerfile for nginx : 

```bash
FROM nginx
COPY default.conf /etc/nginx/conf.d/default.conf
```
And for lazy people like me, an SSL generator script (gen-ssl.sh) : 

```bash
#!/bin/bash

IP="stirling"
SUBJECT_NGINX="/C=FR/ST=France/L=Paris/O=btw/OU=CA/CN=${IP}"

function generate_nginx () {
    echo "$SUBJECT_NGINX"
    openssl req -x509 -nodes -days 3685 -newkey rsa:2048 -subj "$SUBJECT_NGINX" -keyout server.key -out server.crt
}

generate_nginx
```

Okay that solution is ugly because it uses 2 reverse proxy which is not the best, but it works and is really secure because nobody will be able to access your Stirling service with HTTP but only with HTTPS.

**Comment by ZuluPilgrim** [comment]
I am using NginX Proxy Manager and have no idea how to fix it with that.

What is strange is that it was working until I redployed the container.

**Comment by ZuluPilgrim** [comment]
I rolled back to frooodle/s-pdf:0.23.1 and all is well again.

**Comment by IamTaoChen** [comment]
> Until these calls are resolved, you can add this line to your domain-ssl.conf :
> 
> ```
> # Add Content-Security-Policy to force use of HTTPS
> Header always set Content-Security-Policy "upgrade-insecure-requests;"
> ```
> 
> Then reload your apache2 configuration.

After I add this, the websitete is super slow.

<img width="734" alt="image" src="https://github.com/Stirling-Tools/Stirling-PDF/assets/42793494/2b75ffd4-7dac-4c32-a072-7c34e0aff2a2">

**Comment by mkamranmazhar** [comment]
Any update?
HTTP is working fine from http://154.12.224.81:8001
HTTPS is still not working https://pdf.shinetechpro.com

new container start with new image.

**Comment by Frooodle** [comment]
Can someone try the image 
``latest-test``

and see if that produces any different result after clearing cache etc too

**Comment by trogau** [comment]
Pulled the latest image and restarted it under my reverse proxy (Apache) and it looks exactly as expected now (and I forgot to clear the cache) -so one of those changes seems to have done the trick!

**Comment by Frooodle** [comment]
did like 4 changes now to figure out which did it! haha

**Comment by Frooodle** [comment]
``latest-test2`` Can you test this, should let me know which change was cause

**Comment by trogau** [comment]
@Frooodle that one also works fine for me

**Comment by Frooodle** [comment]
After cache clear? :P

**Comment by Frooodle** [comment]
Let me wait for one more user to test both these images ``latest-test2`` first ideally 
and then ill merge

**Comment by trogau** [comment]
> After cache clear? :P

hah yep cleared cache this time!

**Comment by Frooodle** [comment]
alright just made a 0.24.5 lets see if it works

**Comment by mkamranmazhar** [comment]
![askseotools-pdf](https://github.com/Stirling-Tools/Stirling-PDF/assets/106512746/f2f12fce-8f6e-4d8b-b13e-619cc6cbeafa)

All fixed now.
HTTP/HTTPS both working fine now.

Thanks @Frooodle .

**Comment by haarhoff-frs** [comment]
I'm using 0.24.5, the login page now looks okay, but I'm still getting errors:
![Screenshot 2024-05-23 081552](https://github.com/Stirling-Tools/Stirling-PDF/assets/89089047/8a913af3-d5d1-493b-9a35-eafb940a2eb6)

Plus, single sign on with Azure Entra is not working either, there still seems to be a problem with the https URL: 

> AADSTS50011: The redirect URI 'http://mypage.com:443/login/oauth2/code/oidc' specified in the request does not match the redirect URIs configured for the application

**Comment by Ludy87** [comment]
> I'm using 0.24.5, the login page now looks okay, but I'm still getting errors: ![Screenshot 2024-05-23 081552](https://private-user-images.githubusercontent.com/89089047/333061167-8a913af3-d5d1-493b-9a35-eafb940a2eb6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY0NDY4OTUsIm5iZiI6MTcxNjQ0NjU5NSwicGF0aCI6Ii84OTA4OTA0Ny8zMzMwNjExNjctOGE5MTNhZjMtZDVkMS00OTNiLTlhMzUtZWFmYjk0MGEyZWI2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIzVDA2NDMxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQyNjdhZDg5MWJhNTI0ODgxNjc5MDViNWQ3NmMxODc0MmNjY2FiYThmZDNhYmM1MDRiZjI1YTNkMjcyNjkyODcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.dvh7I1_l0Kd4zmunmkA7vu3gozbX2exj_q8Y3S7-9nk)
> 
> Plus, single sign on with Azure Entra is not working either, there still seems to be a problem with the https URL:
> 
> > AADSTS50011: The redirect URI 'http://pdf.haarhoff.eu:443/login/oauth2/code/oidc' specified in the request does not match the redirect URIs configured for the application

That's another mistake.

**Comment by thokich** [comment]
Great it works now fine. The Bug is solved
App Version: 0.24.5
Thanks

**Comment by ZuluPilgrim** [comment]
Thanks for that, working like a dream :)
