### ISSUE TITLE
[Bug]: 'Self-hosted login failed' on Windows App but working in browser

### ISSUE THREAD

**Issue by Splinter9410** [Stirling-Tools/Stirling-PDF#5083]
### Installation Method

Docker

### The Problem

Server installed on truenas machine going through reverse proxy. 
Authentication already set and can be accessed on my browser through my domain name. 
Windows App can access my domain name, but fails credentials authentication with error 'Self-hosted login failed'.

### Version of Stirling-PDF

2.0.1

### Last Working Version of Stirling-PDF

2.0.1

### Page Where the Problem Occurred

Windows app

### Docker Configuration

```txt

```

### Relevant Log Output

```txt

```

### No Duplicate of the Issue

- [x] I have verified that there are no existing issues raised related to my problem.

**Comment by Frooodle** [comment]
should be fixed in 2,0.2

**Comment by Splinter9410** [comment]
> should be fixed in 2,0.2

Since I couldnt update my server to 2.0.2 in truenas, I used docker compose via dockge to run 2.0.2. I am still getting the same error

**Comment by Splinter9410** [comment]
In 2.0.2, I also tried to set SECURITY_ENABLELOGIN=false , which disabled credentials in the webUI. However, after adding my domain in Windows App, it still asks for credentials.

**Comment by Splinter9410** [comment]
@Frooodle can this thread be reopened, or should I create a new one?

**Comment by Frooodle** [comment]
Desktop app currently requires credentials to hook up with a external server 
We have another ticket for that

**Comment by Splinter9410** [comment]
> Desktop app currently requires credentials to hook up with a external server We have another ticket for that

my issue is still showing 'Self-hosted login failed' so my thread is relevant, and I have tried proposed workarounds and solutions that did not work.

**Comment by Frooodle** [comment]
Have you tried desktop 2.0.2 installer?

**Comment by Splinter9410** [comment]
> Have you tried desktop 2.0.2 installer?

i installed the one direct from your website for windows

**Comment by Splinter9410** [comment]
this is my compose: 

```
version: "3.3"
services:
  stirling-pdf:
    image: stirlingtools/stirling-pdf:latest
    container_name: stirling-pdf
    environment:
      - SECURITY_ENABLELOGIN=true
      - DISABLE_ADDITIONAL_FEATURES=false
      - SYSTEM_ENABLEANALYTICS=false
      - LANGS=en_GB
      - MAIL_ENABLED=true
      - MAIL_ENABLEINVITES=true
      - MAIL_SMTP_HOST=smtp.gmail.com
      - MAIL_SMTP_PORT=587
      - MAIL_SMTP_USERNAME=email@gmail.com
      - MAIL_SMTP_PASSWORD=pass word here
      - MAIL_SMTP_TLS_ENABLED=true
    ports:
      - 30125:8080
    volumes:
      - ./stirling:/configs #Settings & database
      - ./stirling/tessdata:/usr/share/tessdata #OCR
      - ./stirling/logs:/logs # Application logs
      - ./stirling/pipeline:/pipeline # Automation configs
    restart: unless-stopped
networks: {}
```

**Comment by Frooodle** [comment]
The windows installer had an update roll out last night

**Comment by Splinter9410** [comment]
> The windows installer had an update roll out last night

I just intalled stirling from the website, just to be safe. Still the same outcome

**Comment by b-v-d-e-v** [comment]
@Frooodle
We are testing with the new V2 server in docker and the windows desktop app too.
Having the same (desktop and server 2.0.2)

* Login in Browser works
* App Login fails with:

<img width="421" height="460" alt="Image" src="https://github.com/user-attachments/assets/77ebfdee-877f-4fcf-b85d-3788b9b26011" />

Be aware: we are on http on a specific port (due to testing)

**Comment by Splinter9410** [comment]
@Frooodle Can we reopen this thread?

**Comment by b-v-d-e-v** [comment]
> The most common workaround is to set `SECURITY_ENABLELOGIN=false` in your Docker configuration and restart the container—this allows the Windows app to connect and log in successfully, while browser login may still require credentials 

I think this is just a misleading Bot-Answer?!? The Desktop-App explicitly requires an enabled login!

**Comment by Splinter9410** [comment]
@Frooodle Recently updated the server to version 2.1.0, and I redownloaded the desktop app from the website, and I am still getting 'Self-hosted Login Failed'. WebUI all good.

**Comment by NoirPi** [comment]
I have Version 2.1.1 on the server side and installed the windows app just today...
And i get the login failed notification.

in the developer console of the app i can see the following:


`<h2>HTTP ERROR 404 No static resource api/v1/proprietary/ui-data/login.</h2>
<table>
<tbody><tr><th>URI:</th><td>/api/v1/proprietary/ui-data/login</td></tr>
<tr><th>STATUS:</th><td>404</td></tr>
<tr><th>MESSAGE:</th><td>No static resource api/v1/proprietary/ui-data/login.</td></tr>
<tr><th>SERVLET:</th><td>dispatcherServlet</td></tr>
</tbody></table>
`

**Comment by Frooodle** [comment]
Does your server have login enabled? it shouldnt get 404 on that address if thats the case

**Comment by NoirPi** [comment]
After a full reinstall I got it working!

It's possible that I messed up the First setup.

**Comment by b-v-d-e-v** [comment]
I updated everything to 2.1.2 but unfortunately it's still not working:

<img width="665" height="90" alt="Image" src="https://github.com/user-attachments/assets/29d1c474-fde9-4c46-9180-0ccb57c4784d" />

**Comment by b-v-d-e-v** [comment]
With 2.4.0 (server and desktop) the login from the windows desktop app is still not possible.

My stirling server (in the container) has no specific configuration besides the "Login enabled = true"
I switched from a custom port to the default 80 (since the selfsigned cert for https does not work)

Any help would be great!

@NoirPi What does "full reinstall" mean? The desktop app or the server?

**Comment by Frooodle** [comment]
Hmm I will check this again we aim to do another release tomorrow morning 
I will dedicate my tonight to looking into this if I have a test installer I will provide it here to confirm fixes later today before release

**Comment by NoirPi** [comment]
@b-v-d-e-v full reinstall of the server is what I did

**Comment by Splinter9410** [comment]
> [@b-v-d-e-v](https://github.com/b-v-d-e-v) full reinstall of the server is what I did

were you getting the "self-hosted login failed" message in your Windows App? 

I did a reinstall via dockge, and it did not work.

**Comment by NoirPi** [comment]
Yes I did but there's a major difference in our Setups... I installed it in an lxc Container without docker and After I did it again it worked. 

> > [@b-v-d-e-v](https://github.com/b-v-d-e-v) full reinstall of the server is what I did
> 
> were you getting the "self-hosted login failed" message in your Windows App? 
> 
> I did a reinstall via dockge, and it did not work.

**Comment by Splinter9410** [comment]
> Yes I did but there's a major difference in our Setups... I installed it in an lxc Container without docker and After I did it again it worked.
> 
> > > [@b-v-d-e-v](https://github.com/b-v-d-e-v) full reinstall of the server is what I did
> > 
> > 
> > were you getting the "self-hosted login failed" message in your Windows App?
> > I did a reinstall via dockge, and it did not work.

Thanks for the information. Perhaps it would help the devs during their investigation. Glad theyre looking into it now

**Comment by Frooodle** [comment]
Can you test if this helps at all? 
https://github.com/Stirling-Tools/Stirling-PDF/releases/download/v2.2.1/test-installer.msi

(its a version of 2.4.1 beta stored in old release since github doesnt let me upload here)

**Comment by b-v-d-e-v** [comment]
thanks a lot for looking into this!

I installed the test version you provided. Now i get a "502 - Bad Gateway" so it somehow changed.

What I observed is:
* I'm using an alias to login http://pdf.bv.mycompany.de:8090
* When i try to talk to the hostname directly it does not find the server at all (http://stirlingpdf01:8090)

Accessing the webui is possible for both without any issues.

<img width="907" height="899" alt="Image" src="https://github.com/user-attachments/assets/0ee8ce10-1f13-4a17-9a88-a7bc2c67b679" />

(if i klick on the http://stirlingpdf01:8090/api/v1/info/status link is shows the propper json with status "up")

The host is airgapped - so no internet connection possible.

With the alias the logs looks much better:

<img width="914" height="725" alt="Image" src="https://github.com/user-attachments/assets/65bd8d72-73c7-46e5-921d-cddcd0386e06" />

But ending with the 502

**Comment by Splinter9410** [comment]
> Can you test if this helps at all? https://github.com/Stirling-Tools/Stirling-PDF/releases/download/v2.2.1/test-installer.msi
> 
> (its a version of 2.4.1 beta stored in old release since github doesnt let me upload here)

When I submit my credentials, instead of the usual "Self-hosted login failed.", I get "Network error: error sending request for url (https://pdf.domain.com/api/v1/auth/login): error trying to connect: The message received was unexpected or badly formatted. (os error -2146893018)"

**Comment by Frooodle** [comment]
Thanks will try have another version to test in few hours

**Comment by Frooodle** [comment]
https://github.com/Stirling-Tools/Stirling-PDF/releases/download/v2.2.1/test2.msi

**Comment by Frooodle** [comment]
let me know if any different results for this one

**Comment by Splinter9410** [comment]
I'm still getting the same error:

Network error: error sending request for url (https://pdf.domain.com/api/v1/auth/login): error trying to connect: The message received was unexpected or badly formatted. (os error -2146893018)

**Comment by Frooodle** [comment]
Is this a old https Or anything? Do you know what TLS it uses?

**Comment by Splinter9410** [comment]
> Is this a old https Or anything? Do you know what TLS it uses?

Ok so interesting development. My laptop (which is less stable) is still facing the issue (os error -2146893018), but I just tried both test-installer.msi and test2.msi on my desktop, and it is working now (didn't encounter Self-hosted login failed or os error). 

will these test apps become official releases?

**Comment by leemac91** [comment]
I tested the update on different systems and it worked everywhere. It would be awesome to get a public release asap :)

**Comment by Frooodle** [comment]
Great! I plan to do an official release in about 3 hours

**Comment by Frooodle** [comment]
Can you please test with 2.4.1 desktop app!

**Comment by Splinter9410** [comment]
> Can you please test with 2.4.1 desktop app!

Thanks. Its working now. I finally pulled the trigger and reinstalled Windows 11 on my laptop, so its working now too. Both my desktop and laptop works with the 2.4.1 app!

**Comment by leemac91** [comment]
I just installed 2.4.1 in Prod an managed to login. But after that I saw that in the bottom right corner there is a red dot which says that the backend is offline. Do others have the same problem?

**Comment by b-v-d-e-v** [comment]
Thanks for all your work here!

Sadly it does not help me: `Login failed: 502 Bad Gateway`

What I tried:
* Reinstalling the desktop app on my machine
* New install the desktop app on another machine

What I checked:
* The docker log does not show any activity (if I log in via the browser I can see expected lines about JWTs, License check, ...) so the DesktopApp can not talk to the server at all?

**Comment by b-v-d-e-v** [comment]
ok - yet another very important learning!

After a call with our it-network-team:

If I disable our corp proxy I can login!
If i re-enable it - I can continue working.

There seem to be no issues in the proxy logs and if i use the dev-tools from the desktop app I can perfectly see the api/status as I already said ... so till now I've never cared about proxy things...

Any idea what's that special during auth?

**Comment by Frooodle** [comment]
resolved as of 2.4.1 @b-v-d-e-v  sorry can you have that as a new ticket i want to ensure the original ones are closed
I will check what is going on with that though so good extra info!
